### ISSUE TITLE
MapsFragment (Deobfuscated class name), (67 Crashes)

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#115]
http://crashes.to/s/c005d1ecbd4

This crash happens at 222 images on a Samsung. 

It was not happening when they were running the app inside of a container app. 

Fabric Issues #31
[org.greenstand.android.treetracker_issue_31_crash_5B657A7701C300013CC3608AF6B75315_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/2263416/org.greenstand.android.treetracker_issue_31_crash_5B657A7701C300013CC3608AF6B75315_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
This is not related to the maps, but rather something turning up null in the onMapReady method, where points are queried.

Tracing the stack trace, the crash is actually coming from a call to Log.e().  So that's either
			`	Log.e("time_for_update", treeCursor.getString(treeCursor.getColumnIndex("_id")));
` or
				`Log.e("issynced", Boolean.toString(isSynced));`

I bet it's the first one.  The reason being, the _id field is not String but rather a Long.  

That's also quite the wacky error logging statement.

**Comment by deepwinter** [comment]
Given the above, the crash at 222 images makes no sense, which places us instead in the zone of Android weirdness..  Calling for a string when you have an int would lead to a flaky pointer variable, which makes sense for the unreliable error condition.
