### ISSUE TITLE
GPS Accuracy -Searching- rename- visualize 

### ISSUE THREAD

**Issue by ghost** [Greenstand/treetracker-android#172]
App blocks users from collecting bad data by blocking the camera feature when the GPS accuracy is above 10. The problem is that when people turn the app on while inside a building, they think it is broken.

There needs to be something to show that the app is searching for the GPS signal.

**Comment by Davidezrajay** [comment]
What should it say? 
Can we represent it searching and reaching percent required visually?

**Comment by peacengn** [comment]
How about "Accurate Location: Yes"? 

Yes - within 10 meters
No - outside of 10 meters

**Comment by Davidezrajay** [comment]
Sometimes the phones just won't get any reception at all... 

The advantage of having the number is that the user can see how they are from the requirement the phone is. This could also be represented with something visual.

**Comment by deepwinter** [comment]
A common way to visualize GPS accuracy is to use a transparent circle with a radius equal to the accuracy. Once the accuracy is small enough to allow logging, you could change the color from orange to green, or change the graphic from a circle to a target or sighing glyph, for instance.

**Comment by peacengn** [comment]
I actually have that implemented in the design mockups. Green for when the accuracy is good for logging, red for when it isn't.

**Comment by deepwinter** [comment]
The mockups show a blue circle with text that changes color.  I am suggesting to consider if customizing the map annotation itself further could further achieve the goals.

**Comment by peacengn** [comment]
Pardon, that is an old mockup. I have new mockups since then that I haven't been able to merge. The new mockups definitely have red transitioning green.

**Comment by peacengn** [comment]
![cursor colors](https://user-images.githubusercontent.com/20362715/53388865-b42cc080-3941-11e9-837b-e2377640402c.png)

**Comment by deepwinter** [comment]
+:+1:

**Comment by deepwinter** [comment]
These mockups are solid, nice work.

A couple of thoughts:  The direction arrow within the location target might not be useful.  You might consider a cross hairs instead.  Maybe there is a reason you want the direction arrow, but remember not all phones have compasses in them.

The tree icons are nice, but make sure to mock this up with hundreds in very close proximity.  Even the three you have here might be fairly far apart.  It will look very different when there are several hundred nearby, and the design you currently have might blend into an amorphous blob of green rather than looking like trees or points.  It's also essential to have a visual strategy for handling clusters of points, because the map will not work well beyond a certain number of markers.

**Comment by Davidezrajay** [comment]
Super cool @peacengn. This is an excellent place to load mockups.  

When in doubt, we need to use as close to universal design standards as possible.

This is the standard... It does not tell the entire story.
![img_1167](https://user-images.githubusercontent.com/25363572/53387944-ba1ca480-3935-11e9-888a-136955747050.JPG)

**Comment by Elforama** [comment]
In terms of handling clusters of trees, I think Google maps solved this rather well. 'star' a bunch of locations close to each other and you'll notice as you zoom out some will disappear. If you zoom out enough it may only show 1 marker.

**Comment by Davidezrajay** [comment]
User feedback on the current version: 
_Earlier this week I took a photo of a ‘tree’ at the Justdiggit office, which worked, but now I’m home: I login and I still see the map around the office (not where I am now). When pushing ‘Add tree’ it says ‘Insufficient GPS accuracy’ and GPS Accuracy 88 meters.
After 10 seconds it switches to GPS Accuracy 5 meters (but then again to GPS accuracy 75 meters..). It’s changing all the time. That confuses me.
The moment it changes to GPS Accuracy 5 meters again, I’m able to take a photo. It works! Nice!_

**Comment by arunbakt** [comment]
Is this still relevant or should we close it. Let me know. I can either work on this one or close it

**Comment by Davidezrajay** [comment]
@arunbakt This still needs some UX work but is a big one that needs to be taken care of.

**Comment by arunbakt** [comment]
From observing the ticket, I see the mockup shows the following changes:

1. The planter thumbnail picture is removed and replaced with the cloud upload icon
2. Clicking on the upload icon on the map fragment syncs the trees and the uploaded tree count is shown in a red label on top of the cloud sync icon.
3. The add tree button is replaced with a camera icon
4. The map markers for trees show a tree icon instead of the google's default icon.
5. Default to google's behavior of showing only one tree icon for a clustered planted trees when zoomed out. On zooming in well enough will show the distinct trees icons representing each tree. 
6. Existing red navigation button is removed.

Is my above observation above correct?

**Comment by shubhamk008** [comment]
Had a small observation. For medium location accuracy, we could look at using the mango color (#FFA500) from our palette instead of orange. Road signs (like red for no parking, yellow for speed limit, green for medical station ahead) and traffic lights subliminally makes us perceive yellow to be a median color. Also, distinguishing orange and red on low-end display devices can be tricky at certain times.
