### ISSUE TITLE
Revise App User Flow Diagram

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#178]
This diagram should be updated.

[App User Flow Diagram.pdf](https://github.com/Greenstand/treetracker-android/files/2602806/App.User.Flow.Diagram.pdf)

https://drive.google.com/file/d/1y3DibDYpUyYwv5UxnNfcmrbhwmdI-c4w/view?usp=sharing

The flow corrected, we are looking for a revised, and visually appealing version of the same flow diagram. 

Here is what needs to change:
It needs to be:
- Easy to understand
- Have the data page
- Sync function added
- Updated to show changes with last revision (removed the red lines)
- Be easy to edit
- Be submitted as a pull request to: https://github.com/Greenstand/treetracker-android/Design

**Comment by Peacenux** [comment]
Here is the new user flow. Let me know if this solves the problem

[Tree Tracker - User Flow_ New Design.pdf](https://github.com/Greenstand/treetracker-android/files/2604827/Tree.Tracker.-.User.Flow_.New.Design.pdf)

**Comment by sebastiangaertner** [comment]
Is there a collaborative tool for User Flow Diagrams?

**Comment by Peacenux** [comment]
Not too sure for a free program with unlimited shared users and tasks.

**Comment by amrutamaliux** [comment]
App Flow: (Feel free to edit and comment)
https://docs.google.com/drawings/d/1UQ1ajxMUdx6gfxGCzcHR9uAayYN4nDE7lyitHghDdyY/edit

**Comment by Peacenux** [comment]
@amrutamaliux Your app flow looks great. It definitely helps visualizing the current app right now with your minor additions for future features. Let's keep your app flow open for history tracking.

In my new app flow/user flow here, I made some revisions from the previous one that I had made. This one has tasks such as:
 _existing_ user login
_new_ user sign up
 _syncing_

https://docs.google.com/drawings/d/1n226oyTkR14dX0xT10rUJf6xS_3lTvc8Gk9soJygGfY/edit?usp=sharing

**Comment by deepwinter** [comment]
@Peacenux In your flow diagram, you only have a user taking a selfie once.   This actually should occur repeatedly after a timeout.  Users are automatically logged out after 2 hours currently, upon which time they re-enter their phone number and take a selfie.  This is an intentional workflow to avoid people logging trees on someone else's account.

**Comment by Peacenux** [comment]
@deepwinter Yes, that is on purpose. Forcing an *existing user to retake a selfie is a security issue itself. So person 1's login info is the same, but their selfies _change_ every time they login? What if person 2 knows person 1's login credentials and then person 2 uses their own face to override & replace person 1's original selfie? 

- here are my screenshots to show the issue of retaking a selfie every time someone new or an existing user logs in. Same login credentials, new selfie. 
![login-retake-selfies](https://user-images.githubusercontent.com/20362715/48974036-d4c34280-f001-11e8-84d8-abbe3d2a2e35.png)



I'm proposing that person 1 with their login info and their own *original selfie is on _every_ single page. Person 1 can only change their selfie specifically in the "my profile" page when they choose to edit their login info. --Shown my wireframes.--

**Comment by deepwinter** [comment]
@Peacenux There is no explicit 'login' on the platform, by design.  It works differently from the using registration/login you might be used to.  Trees planted are linked to phone number or email at the moment they are recorded onto the phone, the user image is so we can verify who is holding the phone when they type in a particular phone number.  The selfies are all logged along with each time, just like the phone number, so there is no 'replacing' another person's selfie.  It's just whoever is using the phone at that moment.  When trees are uploaded, they are linked to the phone number + selfie that originally logged them, not the latest one.

This system was created to control for a number of common manipulative use cases where one user authorizes into the app on multiple phones, and then has other users do the planting, thus taking credit for all the trees planted.  It's a very different usage scenario.

**Comment by Peacenux** [comment]
So is this the process?

1. Only one phone number on one phone, but different people logging in using the same phone number and phone. 
2. System is designed to have a new user for every single login-with the same phone number.
3. Only the current selfie at the present time, will be used for authentication. 
4. Trees planted are linked to phone number/organization, not user. Users just show proof that they've planted a tree(s) to show proof to the organization leader. 

Summary: Same phone but only one phone number on it, same phone number can have many users, new selfies every login, all trees linked to the same phone number, all users are grouped into the same phone number/organization.

**Comment by Peacenux** [comment]
Thanks. Glad this discussion is here for everyone to read. Since this discussion is public it can help future volunteers who are confused, like me, to have a better understanding of the login process.

**Comment by peacengn** [comment]
![1 2 4-block](https://user-images.githubusercontent.com/20362715/53383117-542b1f80-392b-11e9-9a4f-8bac91076acb.png)

Hopefully this should solve the login issues.

**Comment by Davidezrajay** [comment]
Thank you @peacengn for taking the time to figure this one out!

**Comment by Davidezrajay** [comment]
![User flow Diagram](https://user-images.githubusercontent.com/25363572/55097130-15929d00-5070-11e9-90b1-cd7394546c4b.png)
