### ISSUE TITLE
Wireframes: Tree Gallery "Data Page" 

### ISSUE THREAD

**Issue by ghost** [Greenstand/treetracker-android#188]
**Final designs: colors, text, images, fonts, etc will be added in final draft.** 

![android - tree list](https://user-images.githubusercontent.com/20362715/48965655-49e93600-ef76-11e8-9f07-a408f9a3d00c.png)

**Comment by deepwinter** [comment]
Nice ideas here.  I want to point out though that this design might not work out too well in the field, where we are talking more like thousands of trees rather than 10 or 20.  You might want to go with an image grid arranged by date, and then just show the location on the map if they want to drill down.  The lat/lng coordinate numbers themselves don't have a lot of use.

**Comment by Peacenux** [comment]
Ah yes, an image grid to display multiple photos in a row/column.

**Comment by Peacenux** [comment]
![android - tree gallery 1](https://user-images.githubusercontent.com/20362715/48965943-9cc5ec00-ef7c-11e8-9fbf-4c1e6bbd8252.png)

**Comment by LaviniaDragunoi** [comment]
This is great! We could keep the date and time of each image exactly under the image in 2 rows, first with the date and under the hour. 
 The date could help user to see each tree details.
What do you think about this @deepwinter, @Peacenux ?

**Comment by peacengn** [comment]
New design will have a grid layout like @deepwinter suggests. I'm also open to adding a small description that displays date and time.
