### ISSUE TITLE
GPS ACCURACY not displayed

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#246]
Accuracy is not showing on the initial map (under ADD TREE button). 
The app is recording accuracy but not displaying it.

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-android/issues/172

**Comment by deepwinter** [comment]
from Ezra:
It doesn’t seem to turn green.. stays red but allows you to take the photo... photo shows up with a god accuracy of 6 or so

**Comment by deepwinter** [comment]
@Elforama I see this happen after I add a tree.  Before adding a tree I have accuracy data, afterwards its not reappearing.

**Comment by deepwinter** [comment]
In MainActivity we have

`        if (fragmentMapGpsAccuracy != null) {
`

Since we are updating the accuracy text on the maps fragment from the main activity, and we know we are still getting location updates, I am guessing that something along the lines of this variable going null incorrectly is resulting in the accuracy not updating on the maps view.  Or at least this is the part of the code to look at.

This bug pops up after you have added a few trees.

**Comment by deepwinter** [comment]
This needs to be fix, since the accuracy gets stuck on red even when it should be green.

**Comment by deepwinter** [comment]
well, the view variables for GPS info are not null, but though they are being set in code, they are not updating.  It's not clear to me why this would be.
