### ISSUE TITLE
Sync stopping on leaving the app or on Android lock screen or screen saver 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#315]

**Comment by Elforama** [comment]
Do we want this? It's currently not implemented.

**Comment by deepwinter** [comment]
We need to further define the feature in terms of what's available.  Running in a background service is probably necessary for big loads of trees, but there are concerned about draining user batteries, etc.

**Comment by Elforama** [comment]
For background downloads we probably want to look into using the Android WorkManager as well as a service as @deepwinter mentioned. It can allow us to specify under what conditions something should download. E.g. connected to Wifi and charging.

**Comment by deepwinter** [comment]
For uploading though, not downloading.

**Comment by Elforama** [comment]
I don't this should be labeled a bug. Sounds like a feature request.

**Comment by sebastiangaertner** [comment]
i would agree but it makes the app almost impossible to use. 
Take the standard use case: Planter in Africa is in the field... tracks trees (pretty much offline) goes home and maybe if lucky manages to get the sync going. She/he wants to eat or do other things on the phone cause they only have an hour or so to spend online. after trying a couple times they might find out that that is the only way to get the trees uploaded. They might then be able to turn their screensaver or screen lock to a longer period.... or they get tired of it and never use the app again ;-( 
Does the current way of doing it have anything to do with battery consumption? Would we run into issues?

**Comment by Elforama** [comment]
If it's impossible to use then this should be prioritized with detailed explanation of how the feature should work.

So if user clicks sync it should start uploading trees. If they exit the app uploads should continue as long as they have internet. 

What happens if the upload pauses due to them losing internet, and they plant more trees. Once they have internet does it start uploading all old trees and new trees automatically?

Should something happen when trees finish uploading in the background? 

How does a user stop uploads once it has started in the background?

Should uploads stop once internet is lost and to be started manually again? Or should this be automatic?

**Comment by sebastiangaertner** [comment]
i changed it to UX/UI

**Comment by deepwinter** [comment]
I have created #336 to describe an MVP for background sync that is feasible to build for the next release.

**Comment by deepwinter** [comment]
I have created #337 to track UX work on the background sync feature.  

I am closing out this issue as it has been split into more atomic issues now.
