### ISSUE TITLE
MVP background tree upload feature

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#336]
Move the tree sync process into a background service.

The process is started manually by the user using the UI for starting sync (whatever UI that may be).  When the service is running in the background, the required Android notification should read "Treetracker is syncing in the background.  X trees left to sync".

Once started, the sync process runs until completion unless internet connectivity is lost or the user manually stops the sync process using the app UI.  In that case it stops uploads and does not automatically restart.  When internet connectivity is lost, the service displays an Android notification to the user containing the text "Sync stopped: internet connectivity was lost.  You must manually restart.  X trees remaining to sync.".

When sync completes, the service displays an Android notification containing the text "Sync completed.  All trees have been synced."

If internet connectivity is not lost, but an upload error is encountered, the Sync service tries to restart the sync process up to 5 times, with a 30 second delay between each retry.  If there are 5 failures in a row, sync is stopped and the service displays an Android notification with the text "Sync stopped: your internet connection might be too slow.   Please try again with a better connection".   

This version of the sync process does NOT notify a user when internet connectivity becomes available.

**Comment by Elforama** [comment]
Note: WorkManager can possibly help us with this issue: https://developer.android.com/topic/libraries/architecture/workmanager?gclid=Cj0KCQjwrpLoBRD_ARIsAJd0BIVrLBZFJrXMVbyFEubnGm9k2DW8j_nb5IPsN4uSaWjeSixDoi6bjj4aAtZBEALw_wcB

**Comment by sebastiangaertner** [comment]
My suggestion is that we break the sync up in chunks of 50 datapoints (or a chunk size depending on a data speed test??). We can use the field "sequence" in the DB as a monitor for that. Furthermore it would make a lot of sense to clear all trees (after successful upload) from the users phone to avoid huge amounts of data to accumulate on the phones storage. Alternatively only the images gets removed (since they will be available online). 

Show case: 

- 480 trees to be uploaded (sequence = 480)
- after 50 successful uploads the sequence gets set to 430 and the 50 uploaded trees get marked as synced.
- Next batch of 50 trees get uploaded successfully counter goes to 380. 
- Connection breaks on the third batch and the sequence stays at 380. 
- Sync continues in steps of 50 trees and finishes successfully. The number 480 gets written in a table together with a flag and date to show success. The sequence number gets set back to 0. Once the planter tracks again the sequence starts counting again. We could notify the planter when the amount of trees to be synced reaches 500 for example.

 
Would this make any sense to cater for the slowest most unstable connections?

**Comment by Elforama** [comment]
@peacengn @deepwinter We'll need to show a notification for this. What should it looks like, and what information/actions should it show the user?

**Comment by deepwinter** [comment]
@Elforama Can post a link the details whats required and possible in Android notifications at this time?

**Comment by Elforama** [comment]
Questions:

1. Are we expecting the uploads to happen in order of sequence ID?
2. If #1 is yes, then what about the case when an upload fails. In the requirement it says we would stop syncing and wait for better internet, but what if it's corrupt data? Should we skip over it instead to ensure as many trees as possible are uploaded?

**Comment by deepwinter** [comment]
1. This is not a required.
2. Definitely skip over a corrupt data issue.   A corrupt data issue should at the very least be reported into our analytics.

**Comment by Elforama** [comment]
Most, if not all of this ticket is done. I will close this. Any remaining work needed should have its own separate issue.
