### ISSUE TITLE
Blur detection adjustment

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#407]
The blur detection is consistently displaying a warning for many images. 
 
![Screenshot (93)](https://user-images.githubusercontent.com/25363572/72877933-02da0a80-3d0b-11ea-8ef2-cd005a67480c.png)

**Comment by deepwinter** [comment]
It has been determined that the root cause is likely an exception being through on some phones during the blur detection algorithm . The following code returns 0.0 in two places when errors occur.  Instead we should return a passing value rather than failing the image. 

We should return a very large number these cases so that we never fail.

/**
 *  use Brenner's focus metric.
 *  Determined by "office testing" (not real-world)
 *  that the FOCUS_THRESHOLD == 700.
 */
private fun testFocusQuality(): Double {
    try {
        // metric only cares about luminance.
        // for memory limitations, and performance and metric consistency,
        // the image is 200 pixels wide.
        var grayImage = ImageUtils.getGrayPixelFromBitmap(tmpImageFile!!.absolutePath,200) ?: return 0.0
        val q = ImageUtils.brennersFocusMetric(grayImage)
        println(q)
        return q
    } catch (e: java.lang.Exception) {
        println(e)
    }
    // on an error, we return very bad focus.
    return 0.0;
}

**Comment by DominionSoftware** [comment]
I have modified the code so that if an exception occurs, a flag is set in a return Pair<> that indicates the focus metric is not reliable. I was not able to reproduce the false positive in testing on a Google phone nor a Lenovo tablet.

**Comment by DominionSoftware** [comment]
I further modified the code to return nullable Double instead of Pair<>
