### ISSUE TITLE
Reject coordinates reported at 0,0

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#562]
Sometimes the GPS convergence algorithm is reporting coordinates at 0,0.  This is not a valid location, and simply reported because the GPS has not heard from satellites yet.  Any coordinate or 0,0 reported by the GPS should reset the convergence count, such that the moving standard deviation does not start being calculated until all coordinate inputs are not 0,0

**Comment by arunbakt** [comment]
This is happening because there is a convergence timeout leaving the app with no converged data that is within the specified variance range. The code defaults to lat/lon to zero unfortunately to indicate this timeout (didn't realize the mean lat/lon values are used directly on the downstream apps).

Will try and use running mean value for lat/lon even if it the values are not converged. Only thing to remember is the mean lat/lon values may not indicate whether they are converged or not. The location data gathered separately would have to be used to indicate convergence.

**Comment by deepwinter** [comment]
Makes sense.  Good to know we can recover lat/lng for those points if we desire.  That's OK about the timeout, we are making our best effort within constraints to get a good GPS position.  It makes sense that sometimes the GPS wouldn't be able to converge within the time we give it.

**Comment by deepwinter** [comment]
verified that we can recover lat/lng from the full planter tracks for these.
