### ISSUE TITLE
While uploading numbers displayed do not equal total trees

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#869]
"The uploading numbers of captures do not go simultaneously decreasing as it increases on the uploaded part.
I was uploading 151 but as you can see the numbers differs on the screenshot."

Image while uploading:
![image](https://user-images.githubusercontent.com/364622/156419732-8a771083-f642-46b5-90da-f3ade911b86a.png)

Image when upload complete:
https://files.slack.com/files-pri/T6WR1QS8J-F03537F9W3Y/screenshot_20220302-145216.png

**Comment by Elforama** [comment]
This is due to how we upload trees. We need to make a decision on having visuals that give constant feedback, versus accurate numbers displayed.

Since we upload in bundles of 50, technically it should only increment by 50, never smaller amounts. The number that increases by smaller amounts is because it's not the amount uploaded, but the amount of tree images. Tree image uploads contain no data on the tree, so technically it's not fully uploaded until the bundle is.

**Comment by ZavenArra** [comment]
Let's count by image upload for now to give better visual feedback.

In M2.2 we'll do a more complete solution, by pre-computing known URLs for images and uploading the bulk pack _first_

**Comment by ZavenArra** [comment]
duplicate of #870
